---
# vars file for osp.servers
osp_startup_timeout: 600
osp_servers:
  frontend:
    cloud: ospcloud
    int_network: int_network
    ext_network: ext_network
    name: frontend
    state: present
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m2.small
    security_group: frontend
    meta:
      - { group: frontends, deployment_name: QA}
  app1:
    cloud: ospcloud
    int_network: int_network
    ext_network: ext_network
    name: app1
    state: present
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m2.small
    security_group: apps
    meta:
      - { group: frontends, deployment_name: QA}
  app2:
    cloud: ospcloud
    int_network: int_network
    ext_network: ext_network
    name: app2
    state: present
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m2.small
    security_group: apps
    meta:
      - { group: frontends, deployment_name: QA}
  db:
    cloud: ospcloud
    int_network: int_network
    ext_network: ext_network
    name: db
    state: present
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m2.small
    security_group: db
    meta:
      - { group: frontends, deployment_name: QA}
