---
- name: Include sensitive vars
# Lets include the vars with credentials
# You should use --ask-vault-pass when running this playbook
  include_vars: vars/credentials.yml

- name: Create Homework Assignment project 
# Use tower module or tower-cli to create Ansible Tower project. Name of the project is specifed in ./vars/main.yml
  tower_project:
    name: "{{ proj_name | default('test')}}"
    description: "{{ proj_description | default('Project created by Config-Tower Ansible Role')}}"
    organization: "{{ org_name | default('Default') }}"
    state: present
    tower_host: "{{ tower_host | default('localhost') }}"
    tower_username: "{{ tower_admin | default('admin') }}"
    tower_password: "{{ tower_password | default('password') }}"
    validate_certs: "{{ tower_ssl_enable }}"

- name: Machine Credential to connect to workstation using openstack.pub
  tower_credential:
    name: "{{ ssh_cred_name }}"
    organization: "{{ org_name | default('Default') }}"
    state: present
    kind: ssh
    tower_host: "{{ tower_host | default('localhost') }}"
    tower_username: "{{ tower_admin | default('admin') }}"
    tower_password: "{{ tower_password | default('password') }}"
    validate_certs: "{{ tower_ssl_enable }}"
    ssh_key_data: "{{ user_cred_path }}"
    username: "{{ user_cred_name }}"

- name: Create Inventory {{static_inventory_name}} in Organization {{org_name}}
  tower_inventory:
    name: "{{static_inventory_name |default('Test')}}"
    description: "{{ static_inventory_description | default('Test Description')}}"
    organization: "{{org_name |default('Default')}}"
    state: present
    tower_host: "{{ tower_host | default('localhost') }}"
    tower_username: "{{ tower_admin | default('admin') }}"
    tower_password: "{{ tower_password | default('password') }}"
    validate_certs: "{{ tower_ssl_enable }}"

- name: Create Group {{group_name}} in static inventory {{static_inventory_name}}
  tower_group:
    name: "{{group_name |default('test')}}"
    description: "{{ group_description |default('test')}}"
    inventory: "{{ static_inventory_name }}"
    state: present
    tower_host: "{{ tower_host | default('localhost') }}"
    tower_username: "{{ tower_admin | default('admin') }}"
    tower_password: "{{ tower_password | default('password') }}"
    validate_certs: "{{ tower_ssl_enable }}"

- name: Add host {{host_name}}  in tower_inventory {{static_inventory_name}}
  tower_host:
    name: "{{host_name}}"
    description: "{{ host_description |default('Test')}}"
    inventory: "{{static_inventory_name}}"
    state: present
    tower_host: "{{ tower_host | default('localhost') }}"
    tower_username: "{{ tower_admin | default('admin') }}"
    tower_password: "{{ tower_password | default('password') }}"
    validate_certs: "{{ tower_ssl_enable }}"

- name: Associate workstation host to group 
  command: | 
    tower-cli host associate --host "{{host_name}}" --group "{{group_name}}"


- name: Tower Creds key file
  tower_credential:
    name: "{{ opentlc_cred_name }}"
    organization: "{{ org_name | default('Default') }}"
    state: present
    kind: ssh
    tower_host: "{{ tower_host | default('localhost') }}"
    tower_username: "{{ tower_admin | default('admin') }}"
    tower_password: "{{ tower_password | default('password') }}"
    validate_certs: "{{ tower_ssl_enable }}"
    ssh_key_data: "{{ user_cred_path }}"
    username: "{{ opentlc_login }}"

- name: Remove secret
  file:
    name: /root/secret.pem
    state: absent

