---
# vars file for roles/config-tower
app_deploy_playbook: site-3tier-app.yml
aws_cred_name: "Creds for AWS instances"
aws_provision_playbook: aws_provision.yml
aws_read_keys: "AWS Access Key"
aws_region_name: "{{ REGION_NAME }}"
aws_smoke_app_playbook: site-smoketest-aws.yml
aws_ssh_playbook: aws_creds.yml
aws_status_playbook: aws_status_check.yml
ec2_dynamic_inventory: "Three tier inventory"
ec2_inventory_source: "Three tier inventory source"
group_name: workstation
host_name: workstation-{{osp_GUID}}.rhpds.opentlc.com
instance_group_name: osp
job_template_aws_provision: "Provision Prod Env"
job_template_aws_ssh_keys: "SSH keys three tier app"
job_template_aws_status_check: "Check the status of AWS instances"
job_template_name_3tier_app: "3tier app deployment on QA Env"
job_template_name_3tier_app_aws: "3 tier app on Prod"
job_template_name_osp_instances_delete: "Nuke QA Env"
job_template_name_osp_instances: "Provision QA Env"
job_template_smoke_aws: "Smoke test Prod env"
job_template_smoke_osp: "Smoke test QA Env"
opentlc_cred_name: "Opentlc key"
org_name: Default
osp_instances_delete_playbook: site-osp-delete.yml
osp_instances_playbook: site-osp-instances.yml
osp_smoke_playbook: site-smoke-osp.yml
path_to_scm_inventory: scm_inventory
password: r3dh4t1!
proj_name: "Homework Assignment"
scm_branch: master
scm_inventory_source: "SCM three tier inventory source"
scm_url: "{{ github_repo }}"
ssh_cred_name: "Connect_to_workstation"
static_inventory_name: scm_inventory
tag_filters: "tag:instance_filter=three-tier-app-{{ EMAIL }}"
user_cred_name: "cloud-user"
user_cred_path: "/root/.ssh/openstack.pem"
user_name: admin
vault_name: yum_repo_vault
workflow_template_name: cicd_workflow
tower_host: "https://tower1.1ad9.example.opentlc.com"
tower_admin: "admin"
tower_ssl_enable: false
tower_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63376339663238373233303933653938346563643964616663343130343431383239656133643731
          3339373632343064383662613137613562363036633036320a656638356339653566623135666438
          35316636663264626433333561653766393430656533623366323562373439383334366463623734
          3561653735356633350a653130363238383839393034336133353334323037386663396166613666
          3538
password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          31663332323362336561393335356362636336363734313938336536393361633165353736623632
          6537326530663963393937343530393635636339626164630a633730383238333562353164633334
          34313539376263313738383039656635303365396362623634663465303239653430643538313035
          6330353633666363320a303565353164333163313837666564626263313431396439343963633337
          6535
